
development:
  adapter: sqlite3
  database: db/development.sqlite3
  pool: 5
  timeout: 5000
# development:
#   adapter: postgresql
#   database: wikiful_development
#   encoding: unicode
#   user: wikiful
#   host: localhost
#   pool: 5
#   timeout: 5000

#sqlite is good enough for my simple test

# test:
#   adapter: postgresql
#   database: wikiful_test
#   encoding: unicode
#   user: wikiful
#   host: localhost
#   pool: 5
#   timeout: 5000

test:
  adapter: sqlite3
  database: db/test.sqlite3
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: wikiful_production
  encoding: unicode
  pool: 5
  timeout: 5000